{"cells":[{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":9147,"status":"ok","timestamp":1695633120074,"user":{"displayName":"ANVESH DHAMANE","userId":"06609661519127830441"},"user_tz":-330},"id":"ASWePFV5JQXr","outputId":"faa05adc-d478-41ce-f46b-53994976adc0"},"outputs":[{"name":"stdout","output_type":"stream","text":["Collecting streamlit\n","  Downloading streamlit-1.27.0-py2.py3-none-any.whl (7.6 MB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m7.6/7.6 MB\u001b[0m \u001b[31m42.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hRequirement already satisfied: altair\u003c6,\u003e=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.2.2)\n","Requirement already satisfied: blinker\u003c2,\u003e=1.0.0 in /usr/lib/python3/dist-packages (from streamlit) (1.4)\n","Requirement already satisfied: cachetools\u003c6,\u003e=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (5.3.1)\n","Requirement already satisfied: click\u003c9,\u003e=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.1.7)\n","Requirement already satisfied: importlib-metadata\u003c7,\u003e=1.4 in /usr/local/lib/python3.10/dist-packages (from streamlit) (6.8.0)\n","Requirement already satisfied: numpy\u003c2,\u003e=1.19.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.23.5)\n","Requirement already satisfied: packaging\u003c24,\u003e=16.8 in /usr/local/lib/python3.10/dist-packages (from streamlit) (23.1)\n","Requirement already satisfied: pandas\u003c3,\u003e=1.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.5.3)\n","Requirement already satisfied: pillow\u003c10,\u003e=7.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (9.4.0)\n","Requirement already satisfied: protobuf\u003c5,\u003e=3.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.20.3)\n","Requirement already satisfied: pyarrow\u003e=6.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (9.0.0)\n","Requirement already satisfied: python-dateutil\u003c3,\u003e=2.7.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.8.2)\n","Requirement already satisfied: requests\u003c3,\u003e=2.18 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.31.0)\n","Requirement already satisfied: rich\u003c14,\u003e=10.14.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (13.5.2)\n","Requirement already satisfied: tenacity\u003c9,\u003e=8.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.2.3)\n","Requirement already satisfied: toml\u003c2,\u003e=0.10.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.10.2)\n","Requirement already satisfied: typing-extensions\u003c5,\u003e=4.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.5.0)\n","Requirement already satisfied: tzlocal\u003c6,\u003e=1.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (5.0.1)\n","Collecting validators\u003c1,\u003e=0.2 (from streamlit)\n","  Downloading validators-0.22.0-py3-none-any.whl (26 kB)\n","Collecting gitpython!=3.1.19,\u003c4,\u003e=3.0.7 (from streamlit)\n","  Downloading GitPython-3.1.37-py3-none-any.whl (190 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m190.0/190.0 kB\u001b[0m \u001b[31m19.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hCollecting pydeck\u003c1,\u003e=0.8.0b4 (from streamlit)\n","  Downloading pydeck-0.8.1b0-py2.py3-none-any.whl (4.8 MB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m4.8/4.8 MB\u001b[0m \u001b[31m88.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hRequirement already satisfied: tornado\u003c7,\u003e=6.0.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (6.3.2)\n","Collecting watchdog\u003e=2.1.5 (from streamlit)\n","  Downloading watchdog-3.0.0-py3-none-manylinux2014_x86_64.whl (82 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m82.1/82.1 kB\u001b[0m \u001b[31m10.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hRequirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair\u003c6,\u003e=4.0-\u003estreamlit) (0.4)\n","Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair\u003c6,\u003e=4.0-\u003estreamlit) (3.1.2)\n","Requirement already satisfied: jsonschema\u003e=3.0 in /usr/local/lib/python3.10/dist-packages (from altair\u003c6,\u003e=4.0-\u003estreamlit) (4.19.0)\n","Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair\u003c6,\u003e=4.0-\u003estreamlit) (0.12.0)\n","Collecting gitdb\u003c5,\u003e=4.0.1 (from gitpython!=3.1.19,\u003c4,\u003e=3.0.7-\u003estreamlit)\n","  Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m62.7/62.7 kB\u001b[0m \u001b[31m6.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25hRequirement already satisfied: zipp\u003e=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata\u003c7,\u003e=1.4-\u003estreamlit) (3.16.2)\n","Requirement already satisfied: pytz\u003e=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas\u003c3,\u003e=1.3.0-\u003estreamlit) (2023.3.post1)\n","Requirement already satisfied: six\u003e=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil\u003c3,\u003e=2.7.3-\u003estreamlit) (1.16.0)\n","Requirement already satisfied: charset-normalizer\u003c4,\u003e=2 in /usr/local/lib/python3.10/dist-packages (from requests\u003c3,\u003e=2.18-\u003estreamlit) (3.2.0)\n","Requirement already satisfied: idna\u003c4,\u003e=2.5 in /usr/local/lib/python3.10/dist-packages (from requests\u003c3,\u003e=2.18-\u003estreamlit) (3.4)\n","Requirement already satisfied: urllib3\u003c3,\u003e=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests\u003c3,\u003e=2.18-\u003estreamlit) (2.0.4)\n","Requirement already satisfied: certifi\u003e=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests\u003c3,\u003e=2.18-\u003estreamlit) (2023.7.22)\n","Requirement already satisfied: markdown-it-py\u003e=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich\u003c14,\u003e=10.14.0-\u003estreamlit) (3.0.0)\n","Requirement already satisfied: pygments\u003c3.0.0,\u003e=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich\u003c14,\u003e=10.14.0-\u003estreamlit) (2.16.1)\n","Collecting smmap\u003c6,\u003e=3.0.1 (from gitdb\u003c5,\u003e=4.0.1-\u003egitpython!=3.1.19,\u003c4,\u003e=3.0.7-\u003estreamlit)\n","  Downloading smmap-5.0.1-py3-none-any.whl (24 kB)\n","Requirement already satisfied: MarkupSafe\u003e=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2-\u003ealtair\u003c6,\u003e=4.0-\u003estreamlit) (2.1.3)\n","Requirement already satisfied: attrs\u003e=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema\u003e=3.0-\u003ealtair\u003c6,\u003e=4.0-\u003estreamlit) (23.1.0)\n","Requirement already satisfied: jsonschema-specifications\u003e=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema\u003e=3.0-\u003ealtair\u003c6,\u003e=4.0-\u003estreamlit) (2023.7.1)\n","Requirement already satisfied: referencing\u003e=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema\u003e=3.0-\u003ealtair\u003c6,\u003e=4.0-\u003estreamlit) (0.30.2)\n","Requirement already satisfied: rpds-py\u003e=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema\u003e=3.0-\u003ealtair\u003c6,\u003e=4.0-\u003estreamlit) (0.10.2)\n","Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py\u003e=2.2.0-\u003erich\u003c14,\u003e=10.14.0-\u003estreamlit) (0.1.2)\n","Installing collected packages: watchdog, validators, smmap, pydeck, gitdb, gitpython, streamlit\n","Successfully installed gitdb-4.0.10 gitpython-3.1.37 pydeck-0.8.1b0 smmap-5.0.1 streamlit-1.27.0 validators-0.22.0 watchdog-3.0.0\n"]}],"source":["pip install streamlit"]},{"cell_type":"code","execution_count":4,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":532,"status":"ok","timestamp":1695635782563,"user":{"displayName":"ANVESH DHAMANE","userId":"06609661519127830441"},"user_tz":-330},"id":"iECBjkd4JEpM","outputId":"719f1892-123b-438f-909e-c18b7b153496"},"outputs":[{"name":"stdout","output_type":"stream","text":["Writing app.py\n"]}],"source":["%%writefile app.py\n","import pandas as pd\n","import numpy as np\n","import streamlit as st\n","from sklearn.model_selection import train_test_split\n","from sklearn.linear_model import LinearRegression\n","from statsmodels.tsa.arima.model import ARIMA\n","\n","# Synthetic Data Generation\n","dates = pd.date_range(start=\"2020-01-01\", periods=365, freq='D')\n","soil_types = ['sandy', 'loamy', 'clayey']\n","\n","data = {\n","    'date': dates,\n","    'crop_type': np.random.choice(['rice', 'wheat', 'corn'], 365),\n","    'soil_type': np.random.choice(soil_types, 365),\n","    'supply': [i + 3*np.sin(i/15) + 4*np.random.rand() for i in range(365)],\n","    'demand': [i + 3*np.sin(i/30) + 5*np.random.rand() for i in range(365)],\n","    'rainfall': np.random.rand(365) * 100,\n","    'temperature': np.random.rand(365) * 35,\n","    'humidity': np.random.rand(365) * 100\n","}\n","\n","df = pd.DataFrame(data)\n","df['day_of_year'] = df['date'].dt.dayofyear\n","df['profit'] = df['demand'] - df['supply']\n","df['prev_crop'] = df['crop_type'].shift(1).fillna(method='bfill')\n","\n","features = ['day_of_year', 'crop_type', 'prev_crop', 'soil_type']\n","X = df[features]\n","X = pd.get_dummies(X, columns=['crop_type', 'prev_crop', 'soil_type'], drop_first=True)\n","\n","y_supply = df['supply']\n","y_demand = df['demand']\n","\n","X_train, X_test, y_train_supply, y_test_supply = train_test_split(X, y_supply, test_size=0.2, random_state=42)\n","_, _, y_train_demand, y_test_demand = train_test_split(X, y_demand, test_size=0.2, random_state=42)\n","\n","supply_model = LinearRegression().fit(X_train, y_train_supply)\n","demand_model = LinearRegression().fit(X_train, y_train_demand)\n","\n","def predict_supply_demand_gap(date, prev_crop, soil_type):\n","    day_of_year = pd.to_datetime(date).dayofyear\n","    crops = ['rice', 'wheat', 'corn']\n","    crops_with_gap = []\n","\n","    for crop in crops:\n","        input_data_dict = {col: 0 for col in X.columns}\n","        input_data_dict['day_of_year'] = day_of_year\n","        if f'crop_type_{crop}' in X.columns:\n","            input_data_dict[f'crop_type_{crop}'] = 1\n","        if f'prev_crop_{prev_crop}' in X.columns:\n","            input_data_dict[f'prev_crop_{prev_crop}'] = 1\n","        if f'soil_type_{soil_type}' in X.columns:\n","            input_data_dict[f'soil_type_{soil_type}'] = 1\n","\n","        input_data = pd.DataFrame([input_data_dict])\n","\n","        predicted_supply = supply_model.predict(input_data)[0]\n","        predicted_demand = demand_model.predict(input_data)[0]\n","\n","        if predicted_demand \u003e predicted_supply:\n","            crops_with_gap.append(crop)\n","\n","    return crops_with_gap\n","\n","crop_models = {}\n","for crop in ['rice', 'wheat', 'corn']:\n","    crop_df = df[df['crop_type'] == crop]\n","    if not crop_df.empty:\n","        model = ARIMA(crop_df['profit'], exog=crop_df[['rainfall', 'temperature', 'humidity']], order=(5,1,0))\n","        model_fit = model.fit()\n","        crop_models[crop] = model_fit\n","\n","def recommend_best_crop_given_climate(date, prev_crop, predicted_rainfall, predicted_temperature, predicted_humidity, soil_type):\n","    crops_with_gap = predict_supply_demand_gap(date, prev_crop, soil_type)\n","\n","    # Filter out the previous crop from the recommendation list\n","    if prev_crop in crops_with_gap:\n","        crops_with_gap.remove(prev_crop)\n","\n","    if not crops_with_gap:\n","        return \"No new crops with a supply-demand gap for the given date. Consider alternatives.\"\n","\n","    best_crop = None\n","    best_profit = float('-inf')\n","    exog_data = pd.DataFrame({'rainfall': [predicted_rainfall], 'temperature': [predicted_temperature], 'humidity': [predicted_humidity]})\n","\n","    for crop in crops_with_gap:\n","        model = crop_models.get(crop)\n","        if model:\n","            try:\n","                forecast_results = model.get_forecast(steps=1, exog=exog_data)\n","                predicted_profit = forecast_results.predicted_mean.iloc[0]\n","                if predicted_profit \u003e best_profit:\n","                    best_profit = predicted_profit\n","                    best_crop = crop\n","            except Exception as e:\n","                print(f\"Error forecasting for crop {crop}: {e}\")\n","\n","    return best_crop\n","\n","st.title(\"Crop Recommendation System\")\n","D = st.date_input(\"Date\")\n","PC = st.selectbox('Previous Crop',('Rice', 'Wheat', 'Corn'))\n","T = st.number_input(label = \"Temperature\")\n","R = st.number_input(label = \"Rainfall\")\n","H = st.number_input(label = \"Humidity\")\n","S = st.selectbox('Soil Type',('sandy', 'loamy', 'clayey'))\n","best_crop = recommend_best_crop_given_climate(D,PC,T,R,H,S)\n","if st.button(\"enter\"):\n","  st.write(best_crop)"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/"},"id":"JDiSm65UKAH8"},"outputs":[{"name":"stdout","output_type":"stream","text":["35.221.41.72\n","[##................] / fetchMetadata: sill resolveWithNewModule ms@2.1.2 checki\u001b[0m\u001b[K\n","Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.\n","\u001b[0m\n","\u001b[0m\n","\u001b[34m\u001b[1m  You can now view your Streamlit app in your browser.\u001b[0m\n","\u001b[0m\n","\u001b[34m  Network URL: \u001b[0m\u001b[1mhttp://172.28.0.12:8501\u001b[0m\n","\u001b[34m  External URL: \u001b[0m\u001b[1mhttp://35.221.41.72:8501\u001b[0m\n","\u001b[0m\n","\u001b[K\u001b[?25hnpx: installed 22 in 2.249s\n","your url is: https://ten-clocks-train.loca.lt\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:473: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.\n","  self._init_dates(dates, freq)\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: ValueWarning: No supported index is available. Prediction results will be given with an integer index beginning at `start`.\n","  return get_prediction_index(\n","/usr/local/lib/python3.10/dist-packages/statsmodels/tsa/base/tsa_model.py:836: FutureWarning: No supported index is available. In the next version, calling this method in a model without a supported index will result in an exception.\n","  return get_prediction_index(\n"]}],"source":["!streamlit run app.py \u0026 npx localtunnel --port 8501 \u0026 curl ipv4.icanhazip.com"]}],"metadata":{"colab":{"name":"","version":""},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":0}